name: APK bauen

on:
  push:
  workflow_dispatch:

jobs:
  android:
    name: nomal für Android
    runs-on: ubuntu-22.04
    steps:
      - name: Projekt holen
        uses: actions/checkout@v4

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: System-Abhängigkeiten vorbereiten
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip autoconf libtool \
            pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Buildozer und Tools installieren
        run: |
          pip3 install --upgrade pip
          pip3 install --user --upgrade buildozer cython==0.29.36

      - name: Mit Buildozer bauen
        uses: Fisheye/buildozer-action@v0.2
        id: buildozer
        with:
          command: buildozer -v android debug
          buildozer_version: master

      - name: APK ablegen
        uses: actions/upload-artifact@v4
        with:
          name: nomal-apk
          path: bin/*.apk

      - name: Protokoll bei Fehlschlag
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: bau-protokoll
          path: |
            .buildozer/android/platform/build-*/build.log
            .buildozer/**/*.log
          if-no-files-found: ignore
